name: Deploy ESP Web (Static) to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Debug contents
      run: |
        echo "Files in esp-web:"
        ls -la esp-web

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./esp-web
        publish_branch: main
        user_name: Suveen Kumar
        user_email: suveenkumar1997@gmail.com

